---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-app
spec:
  stepTemplate:
    volumeMounts:
      - name: varlibc
        mountPath: /var/lib/containers
  params:
    - name: contextDir
      description: the context dir within source
      default: .
    - name: mavenMirrorUrl
      description: the maven mirrror url
      default: https://repo.maven.apache.org/maven2/
    - name: destinationImage
      description: the fully qualified image name
      default: $(outputs.resources.builtImage.url):$(inputs.params.imageTag)
    - name: dockerFile
      description: the docker file to used for building the application
      default: Dockerfile.jvm
    - name: buildProfile
      description: the docker file to used for building the application
      default: quarkus
    - name: imageTag
      description: image tag
      default: v1.0.0
    - name: tlsVerify
      description: tls verify
      type: string
      default: "false"
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-sources
      image: docker.io/maven:3.6.3-openjdk-11-slim
      workingDir: "/workspace/source/$(inputs.params.contextDir)"
      command:
        - mvn
      args:
        - -DskipTests
        - clean
        - package
        - -P$(inputs.params.buildProfile)
      env:
        - name: user.home
          value: /home/tekton
    - name: build-image
      #image: quay.io/buildah/stable:latest
      image: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      workingDir: "/workspace/source/$(inputs.params.contextDir)"
      resources: {}
      script: |
        buildah --storage-driver=vfs bud \
          --layers --format=docker \
          -f $(inputs.params.dockerFile) -t $(outputs.resources.builtImage.url):$(inputs.params.imageTag) .
      volumeMounts:
        - name: varlibc
          mountPath: /var/lib/containers
    - name: push-image
      image: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      workingDir: "/workspace/source/$(inputs.params.contextDir)"
      resources: {}
      script: |
        buildah --storage-driver=vfs push \
          --tls-verify=$(inputs.params.tlsVerify) \
          --digestfile $(workspaces.source.path)/image-digest $(outputs.resources.builtImage.url):$(inputs.params.imageTag) \
          docker://$(outputs.resources.builtImage.url):$(inputs.params.imageTag)
      volumeMounts:
        - name: varlibc
          mountPath: /var/lib/containers
  volumes:
    - name: varlibc
      emptyDir: {}
