apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-spring
  name: todo-spring
spec:
  type: ClusterIP
  ports:
    - name: 8080-port
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: todo-spring
