apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  resources:
    inputs:
      - name: source
        type: git
      - name: image-out
        type: image  
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
    - name: contextDir
      description: the context dir within source
      default: .
    - name: imageTag
      description: image tag
      default: v1.0.0
  steps:
    - name: ls-build-sources
      image: busybox
      command: ["ls", "-ltr", "/workspace/source/$(inputs.params.contextDir)"]
    - name: update-image-in-yaml
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source/$(inputs.params.contextDir)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo cleaning terminated pods
          find ./$(inputs.params.manifest_dir) -type f -exec sed -i -e s!"image: PIPELINE_REPLACE:latest"!"image: ${IMG}"!g {} \;
          echo -----------------------------------  
      env:
        - name: IMG
          value: $(inputs.resources.image-out.url):$(inputs.params.imageTag)
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source/$(inputs.params.contextDir)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          oc apply -f $(inputs.params.manifest_dir)/deployment.yaml
          oc apply -f $(inputs.params.manifest_dir)/service.yaml
          oc apply -f $(inputs.params.manifest_dir)/route.yaml
          echo -----------------------------------
    # - name: clean-orphan-pods
    #   image: quay.io/openshift/origin-cli:latest
    #   command: ["/bin/bash", "-c"]
    #   args:
    #     - |-
    #       echo cleaning terminated pods
    #       oc delete pods -l app.kubernetes.io/managed-by=tekton-pipelines
    #       echo -----------------------------------



