apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
    - name: contextDir
      description: the context dir within source
      default: .
  steps:
    - name: ls-build-sources
      image: busybox
      command: ["ls", "-ltr", "/workspace/source/$(inputs.params.contextDir)"]
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source/$(inputs.params.contextDir)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          oc apply -f $(inputs.params.manifest_dir)
          echo -----------------------------------
