apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: to-do
  name: to-do
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do
  template:
    metadata:
      labels:
        app: to-do
    spec:
      containers:
        - image: quay.io/ooteniya/tekton-tutorial-greeter:latest
          imagePullPolicy: Always
          name: to-do
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "300m"  
          ports:
            - containerPort: 8080
              protocol: TCP

