apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-spring-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-spring
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization