apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todo-spring
  name: todo-spring
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: todo-spring
    weight: 100

