apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todo-quarkus
  name: todo-quarkus
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: todo-quarkus
    weight: 100

