apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: todo-spring-svcmonitor
  name: todo-spring-svcmonitor
spec:
  endpoints:
  - interval: 5s
    port: 8080-tcp
    scheme: http
  selector:
    matchLabels:
      app: todo-spring